### ISSUE TITLE
can uploadVideo method really work?

### ISSUE THREAD

**Issue by carlhung** [sabas1080/InstagramPi#1]
I am trying to convert instgarm's API using swift language.
I cloned your code and found the uploadVideo method which can not work.
I haven't tried on my pi yet. 
have you tried using your code to upload video?

**Comment by sabas1080** [comment]
Hi

Video work 
https://github.com/sabas1080/InstagramPi/blob/c5978e89dc63df96e599db12d2795aceb06d57be/InstagramPi.py#L58

The conversion is done by means of ffmpeg

**Comment by carlhung** [comment]
I mean videoUpload method from InstagramAPI.
I tried the api doesn't work. And dig into it. The code is weird

**Comment by sabas1080** [comment]
My work is based in the of LevPasha
https://github.com/LevPasha/Instagram-API-python

Unofficial instagram API, give you access to ALL instagram features (like, follow, upload photo and video and etc)! Write on python.

**Comment by carlhung** [comment]
Yes, I know. I googled it and found the code. If you go to the repo, you will see the uploadVideo method doesn't release yet. So, I thought you might have a enhanced version.

**Comment by sabas1080** [comment]
Oh yes, here fix error in video upload

https://github.com/sabas1080/InstagramPi/commit/bdb1f22a41d07a040289add0dc0fe65dc8cca8fe

**Comment by carlhung** [comment]
i believe not.

**Comment by carlhung** [comment]
If you are exactly using:
https://github.com/LevPasha/Instagram-API-python
Then, uploadvideo shouldn't work. The author doesn't implement yet

**Comment by sabas1080** [comment]
Video demo upload from raspberry pi and python

https://www.instagram.com/p/BTFAyHPjp47/?taken-by=xhabas
